version: '3.8'
services:
  db:
    image: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'

    environment:
      MYSQL_ROOT_PASSOWRD: 'root'
      MYSQL_DATABASE: 'test'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'root'
      MYSQL_RANDOM_ROOT_PASSWORD: 'root'